services:
  payroll-service-agent:
    build:
      context: .
      dockerfile: Dockerfile.local
      network: payroll_dns_net
    ports:
      - "8000:8000"
    networks:
      - payroll_dns_net
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  langgraph-playground:
    build:
      context: .
      dockerfile: Dockerfile.local
      network: payroll_dns_net
    ports:
      - "2024:2024"
    networks:
      - payroll_dns_net
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
    command: ["langgraph", "dev", "--host", "0.0.0.0", "--port", "2024", "--allow-blocking"]

networks:
  payroll_dns_net:
    external: true
